openapi: 3.1.0
info:
  title: Customer
  version: '1.0'
  summary: A customer of a bibliothek us someone who can lend items
  description: A person that can be identified and who can lend items.
  contact:
    name: Christian Langmann
    email: c_langmann@gmx.de
servers:
  - url: 'http://localhost:8080/customer'
    description: customer
paths:
  /customers:
    post:
      summary: Create New Customer
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                New Customer Bob Fellow:
                  value:
                    customerId: fe0f656e-f999-4bf8-8cc2-820c43bc1fd5
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      tags:
        - create
        - customer
    parameters: []
  '/customers/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
    get:
      summary: Get Customer Info by Customer ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Get Customer Alice Smith:
                  value:
                    customerId: 2248ebd9-c842-4342-8a4e-59b4220db699
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the customer with the matching customer ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Updated User Rebecca Baker:
                  value:
                    customerId: 2248ebd9-c842-4342-8a4e-59b4220db699
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      tags:
        - customer
        - change
components:
  schemas:
    Customer:
      title: Customer
      type: object
      description: A customer who can lend items
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        customerId:
          $ref: ../model/Uuid.yaml
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        street:
          type: string
        zipCode:
          type: string
        city:
          type: string
      required:
        - customerId
        - firstName
        - lastName
        - email
        - emailVerified
tags:
  - name: change
  - name: create
  - name: customer
